servers=[
  {
    :hostname => "server1",
    :ip => "192.168.200.11",
    :box => "bento/ubuntu-24.04",
    :ram => 4096,
    :cpu => 2
  },
  {
    :hostname => "server2",
    :ip => "192.168.200.12",
    :box => "bento/ubuntu-24.04",
    :ram => 4096,
    :cpu => 2
  }
]

workers=[
  {
    :hostname => "worker1",
    :ip => "192.168.200.22",
    :box => "bento/ubuntu-24.04",
    :ram => 4096,
    :cpu => 4
  },
  {
    :hostname => "worker2",
    :ip => "192.168.200.23",
    :box => "bento/ubuntu-24.04",
    :ram => 4096,
    :cpu => 2
  },
  {
    :hostname => "worker3",
    :ip => "192.168.200.24",
    :box => "bento/ubuntu-24.04",
    :ram => 4096,
    :cpu => 4
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname], primary: true do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
          rsync__exclude: ".git/"

      node.vm.provider "libvirt" do |lv|
          lv.nested = true
          lv.cpu_mode = "host-passthrough"
          lv.memory = machine[:ram]
          lv.cpus = machine[:cpu]
          lv.name = machine[:hostname]

          # turn off inputs
          lv.inputs = []
      end

      args = []
      node.vm.provision "k8s server shell script", type: "shell",
          path: "scripts/k8s_server_provisioning.sh",
          args: args
    end
  end

  workers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
              rsync__exclude: ".git/"

          node.vm.provider "libvirt" do |lv|
              lv.nested = true
              lv.cpu_mode = "host-passthrough"
              lv.memory = machine[:ram]
              lv.cpus = machine[:cpu]
              lv.name = machine[:hostname]
          end
          
          args = []
          node.vm.provision "k8s worker shell script", type: "shell",
          path: "scripts/k8s_worker_provisioning.sh",
          args: args
      end
  end
end