servers=[
  {
    :hostname => "server1",
    :ip => "192.168.100.11",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server2",
    :ip => "192.168.100.22",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server3",
    :ip => "192.168.100.33",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server4",
    :ip => "192.168.100.44",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          # node.vm.provider "virtualbox" do |vb|
          #     vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
          #     vb.customize ["modifyvm", :id, "--cpu", machine[:cpu]]
          node.vm.provider "libvirt" do |lv|
              lv.memory = machine[:ram]
              lv.cpus = machine[:cpu]
          node.vm.provision "shell", inline: <<-SHELL
              sudo timedatectl set-timezone Asia/Dhaka
              sudo apt update
              sudo apt install -y net-tools iputils-ping docker.io openvswitch-switch
              # sudo docker network create --subnet 172.18.0.0/16 vxlan-net
           SHELL
          end
      end
  end
end