servers=[
  {
    :hostname => "server1",
    :ip => "192.168.100.11",
    :box => "bento/ubuntu-22.04",
    # :ssh_port => '2211',
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server2",
    :ip => "192.168.100.22",
    :box => "bento/ubuntu-22.04",
    # :ssh_port => '2222',
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          # node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
          # node.vm.provider "virtualbox" do |vb|
          #     vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
          #     vb.customize ["modifyvm", :id, "--cpu", machine[:cpu]]
          node.vm.provider "libvirt" do |vb|
              vb.memory = machine[:ram]
              vb.cpus = machine[:cpu]
          # node.vm.provision "shell", inline: <<-SHELL
          #     sudo echo "192.168.100.1" | sudo tee -a /etc/hosts
          #     sudo timedatectl set-timezone Asia/Dhaka
          #  SHELL
          end
      end
  end
end