server=[
  {
    :hostname => "server",
    :ip => "192.168.100.11",
    :box => "bento/ubuntu-22.04",
    :ram => 4096,
    :cpu => 4
  }
]

workers=[
  {
    :hostname => "worker1",
    :ip => "192.168.100.21",
    :box => "bento/ubuntu-22.04",
    :ram => 4096,
    :cpu => 4
  },
  {
    :hostname => "worker2",
    :ip => "192.168.100.22",
    :box => "bento/ubuntu-22.04",
    :ram => 4096,
    :cpu => 4
  },
  {
    :hostname => "worker3",
    :ip => "192.168.100.23",
    :box => "bento/ubuntu-22.04",
    :ram => 2048,
    :cpu => 2
  }
]

Vagrant.configure("2") do |config|
  server.each do |machine|
    config.vm.define machine[:hostname], primary: true do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]

      # Setting up private_network to have virtual host
      node.vm.network "private_network", ip: machine[:ip]

      # Setting up synced folder
      node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
          rsync__exclude: ".git/"

      node.vm.provider "libvirt" do |lv|
          lv.nested = true
          # lv.cpu_mode = "host-passthrough"
          lv.memory = machine[:ram]
          lv.cpus = machine[:cpu]

          # turn off inputs
          lv.inputs = []
      end

      args = []
      node.vm.provision "k3s shell script", type: "shell",
          path: "scripts/k3s_server_provisioning.sh",
          args: args
    end
  end

  workers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]

          # Setting up private_network to have virtual host
          node.vm.network "private_network", ip: machine[:ip]

          # Setting up synced folder
          node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
              rsync__exclude: ".git/"

          node.vm.provider "libvirt" do |lv|
              lv.nested = true
              # lv.cpu_mode = "host-passthrough"
              lv.memory = machine[:ram]
              lv.cpus = machine[:cpu]
          end
          
          args = []
          node.vm.provision "k3s worker shell script", type: "shell",
          path: "scripts/k3s_worker_provisioning.sh",
          args: args
      end
  end
end