server=[
  {
    :hostname => "server",
    :ip => "192.168.100.11",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  }
]

agents=[
  {
    :hostname => "agent1",
    :ip => "192.168.100.22",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "agent2",
    :ip => "192.168.100.33",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "agent3",
    :ip => "192.168.100.44",
    :box => "bento/ubuntu-22.04",
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure("2") do |config|
  server.each do |machine|
    config.vm.define machine[:hostname], primary: true do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
          rsync__exclude: ".git/"
      node.vm.provider "libvirt" do |lv|
          lv.memory = machine[:ram]
          lv.cpus = machine[:cpu]

          # turn off inputs
          lv.inputs = []
      end

      args = []
      node.vm.provision "k3s shell script", type: "shell",
          path: "scripts/k3s_server_provisioning.sh",
          args: args
    end
  end

  agents.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.synced_folder "./shared", "/vagrant", type: "rsync",
              rsync__exclude: ".git/"
          node.vm.provider "libvirt" do |lv|
              lv.memory = machine[:ram]
              lv.cpus = machine[:cpu]

          # agent.vm.provision "shell", inline: agent_script
          args = []
          node.vm.provision "k3s agent shell script", type: "shell",
          path: "scripts/k3s_agent_provisioning.sh",
          args: args
          end
      end
  end
end